package in.waghtech.motivationalquotes;

import androidx.appcompat.app.AppCompatActivity;
import androidx.cardview.widget.CardView;
import androidx.core.app.ActivityCompat;
import android.Manifest;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.os.Bundle;
import android.provider.MediaStore;
import android.widget.Toast;
import java.util.Arrays;
import java.util.Collections;

public class MainActivity extends AppCompatActivity {
    verticalViewPager myPager;
    String[] quotes=
            {
                    "Don't cry because it's over, smile because it happened.",
            "Be yourself, everyone else is already taken.",
            "Two things are infinite: the universe and human stupidity. And I'm not sure about the universe.",
            "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.",
            "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
            "A room without books is like a body without a soul.",
            "So many books, so little time.",
            "You only live once, but if you do it right, once is enough.",
            "Be the change that you wish to see in the world.",
            "In three words I can sum up everything I've learned about life: it goes on.",
            "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
            "Don’t walk in front of me, I may not follow. Don’t walk behind me, I may not lead. Walk beside me, just be my friend",
            "No one can make you feel inferior without your consent.",
            "If you tell the truth, you don't have to remember anything.",
            "A friend is someone who knows all about you and still loves you.",
            "Always forgive your enemies, nothing annoys them so much.",
            "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
            "Live as if you were to die tomorrow. Learn as if you were to live forever.",
            "I am so clever that sometimes I don't understand a single word of what I am saying.",
            "Darkness cannot drive out darkness, only light can do that. Hate cannot drive out hate, only love can do that.",
            "To live is the rarest thing in the world. Most people exist, that is all.",
            "Without music, life would be a mistake.",
            "Insanity is doing the same thing, over and over again, but expecting different results.",
            "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
            "We accept the love we think we deserve.",
            "It is better to be hated for what you are than to be loved for what you are not.",
            "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
            "It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.",
            "It is our choices that show what we truly are, far more than our abilities.",
            "Life is what happens to you while you're busy making other plans.",
            "Good friends, good books, and a sleepy conscience: this is the ideal life.",
            "Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).",
            "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.",
            "We are all in the gutter, but some of us are looking at the stars.",
            "If you don't stand for something you will fall for anything.",
            "The man who does not read has no advantage over the man who cannot read.",
            "I have not failed. I've just found 10,000 ways that won't work.",
            "It is not a lack of love, but a lack of friendship that makes unhappy marriages.",
            "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.",
            "I may not have gone where I intended to go, but I think I have ended up where I needed to be.",
            "A day without sunshine is like, you know, night.",
            "I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.",
            "Love all, trust a few, do wrong to none.",
            "If you judge people, you have no time to love them.",
            "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.",
            "For every minute you are angry you lose sixty seconds of happiness.",
            "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
            "It is never too late to be what you might have been.",
            "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.",
            "A reader lives a thousand lives before he dies. The man who never reads lives only one.",
            "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.",
            "If you can't explain it to a six year old, you don't understand it yourself.",
            "Women and cats will do as they please, and men and dogs should relax and get used to the idea.",
            "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
            "Love is that condition in which the happiness of another person is essential to your own.",
            "Sometimes the questions are complicated and the answers are simple.",
            "We don't see things as they are, we see them as we are.",
            "All you need is love. But a little chocolate now and then doesn't hurt.",
            "Everything you can imagine is real.",
            "Today you are You, that is truer than true. There is no one alive who is Youer than You.",
            "Never trust anyone who has not brought a book with them.",
            "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.",
            "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.",
            "Logic will get you from A to Z, imagination will get you everywhere.",
            "One good thing about music, when it hits you, you feel no pain.",
            "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
            "Not all of us can do great things. But we can do small things with great love.",
            "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.",
            "Folks are usually about as happy as they make their minds up to be.",
            "Love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind.",
            "If you only read the books that everyone else is reading, you can only think what everyone else is thinking.",
            "Sometimes people are beautiful. Not in looks. Not in what they say. Just in what they are.",
            "The difference between genius and stupidity is: genius has its limits.",
            "Do what you can, with what you have, where you are.",
            "If you can make a woman laugh, you can make her do anything.",
            "To the well-organized mind, death is but the next great adventure.",
            "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.",
            "Life isn't about finding yourself. Life is about creating yourself.",
            "You don't love someone because they're perfect, you love them in spite of the fact that they're not.",
            "A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.",
            "The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.",
            "Life is like riding a bicycle. To keep your balance, you must keep moving.",
            "Some infinities are bigger than other infinities.",
            "There is no friend as loyal as a book.",
            "Time you enjoy wasting is not wasted time.",
            "Do one thing every day that scares you.",
            "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.",
            "If I had a flower for every time I thought of you, I could walk through my garden forever.",
            "Some people never go crazy. What truly horrible lives they must lead.",
            "Reality continues to ruin my life.",
            "Success is not final, failure is not fatal: it is the courage to continue that counts.",
            "Things change. And friends leave. Life doesn't stop for anybody.",
            "You don’t forget the face of the person who was your last hope.",
            "Go to heaven for the climate and hell for the company.",
            "The reason I talk to myself is because I’m the only one whose answers I accept.",
            "If everyone is moving forward together, then success takes care of itself.",
            "Hope is the only universal liar who never loses his reputation for veracity.",
            "Politics is the art of controlling your environment.",
            "He has achieved success who has worked well, laughed often, and loved much.",
            "Hope is the last thing a person does before they are defeated.",
            "Where there is love there is life.",
            "Advertising is the art of convincing people to spend money they don't have for something they don't need.",
            "Success comes from knowing that you did your best to become the best that you are capable of becoming.",
            "It's time to get real, folks. Hope and change ain't working. Hope and change is not a solution. Hope and change is not a job.",
            "Life in abundance comes only through great love.",
            "The best way to make your audience laugh is to start laughing yourself.",
            "The most important single ingredient in the formula of success is knowing how to get along with people.",
            "I always believe things are going to work out.",
            "Comedy has to be based on truth. You take the truth and you put a little curlicue at the end.",
            "Always bear in mind that your own resolution to succeed is more important than any other.",
            "When someone loves you, the way they talk about you is different. You feel safe and comfortable.",
            "When love and skill work together, expect a masterpiece.",
            "You don't have to be a genius or a visionary or even a college graduate to be successful. You just need a framework and a dream.",
            "Any life is made up of a single moment, the moment in which a man finds out, once and for all, who he is.",
            "Success isn't measured by money or power or social rank. Success is measured by your discipline and inner peace.",
            "The most powerful weapon on earth is the human soul on fire.",
            "It is the ability to take a joke, not make one, that proves you have a sense of humor.",
            "To be successful, you have to have your heart in your business and your business in your heart.",
            "He who has health, has hope, and he who has hope, has everything.",
            "The greatest trap in our life is not success, popularity or power, but self-rejection.",
            "Character develops itself in the stream of life.",
            "Formal education will make you a living, self-education will make you a fortune.",
            "Think twice before you speak, because your words and influence will plant the seed of either success or failure in the mind of another.",
            "The art of simplicity is a puzzle of complexity.",
            "A good teacher can inspire hope, ignite the imagination, and instill a love of learning.",
            "There was never a night or a problem that could defeat sunrise or hope.",
            "Laughter is involuntary. If it's funny you laugh.",
            "It takes half your life before you discover life is a do-it-yourself project.",
            "What we think determines what happens to us, so if we want to change our lives, we need to stretch our minds.",
            "Frustration, although quite painful at times, is a very positive and essential part of success.",
            "If you want to achieve things in life, you've just got to do them, and if you're talented and smart, you'll succeed.",
            "You, yourself, as much as anybody in the entire universe, deserve your love and affection.",
            "The question isn't who is going to let me, it's who is going to stop me.",
            "The greatest sign of success for a teacher is to be able to say, 'The children are now working as if I did not exist'.",
            "The man who has no inner-life is a slave to his surroundings.",
            "It is often said that before you die your life passes before your eyes. It is in fact true. It's called living.",
            "Coming together is a beginning, keeping together is progress, working together is success.",
            "Life is like riding a bicycle. To keep your balance, you must keep moving.",
            "Smile in the mirror. Do that every morning and you'll start to see a big difference in your life.",
            "I have never let my schooling interfere with my education.",
            "Success is simple. Do what's right, the right way, at the right time.",
            "Draw your pleasure, paint your pleasure, and express your pleasure strongly.",
            "Write what you love. Love will hold you through the hard times and hold the world during the good times.",
            "The starting point of all achievement is desire.",
            "A great artist can paint a great picture on a small canvas.",
            "He who is not courageous enough to take risks will accomplish nothing in life.",
            "That's the motivation of an artist - to seek attention of some kind.",
            "Don't aim for success if you want it, just do what you love and believe in, and it will come naturally.",
            "Love is a fire. But whether it is going to warm your hearth or burn down your house, you can never tell.",
            "It takes courage to grow up and become who you really are.",
            "Success consists of going from failure to failure without loss of enthusiasm.",
            "If you look at terrorists, they really have no sense of humor.",
            "Try not to become a man of success, but rather try to become a man of value.",
            "Without music, life would be a mistake.",
            "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.",
            "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.",
            "Expecting something for nothing is the most popular form of hope.",
            "With the past, I have nothing to do, nor with the future. I live now.",
            "Money and success don't change people, they merely amplify what is already there.",
            "I am prepared for the worst, but hope for the best.",
            "It's possible to love a human being if you don't know them too well.",
            "A person with a new idea is a crank until the idea succeeds.",
            "There is a very fine line between loving life and being greedy for it.",
            "A woman knows the face of the man she loves as a sailor knows the open sea.",
            "If you have no critics you'll likely have no success.",
            "Love has no age, no limit, and no death.",
            "Happiness is not something ready made. It comes from your own actions.",
            "I don't want to be interesting. I want to be good.",
            "Whatever you are, be a good one.",
            "Success is a journey, not a destination. The doing is often more important than the outcome.",
            "There are three ingredients in the good life: learning, earning and yearning.",
            "I like the night. Without the dark, we'd never see the stars.",
            "All we have to decide is what to do with the time that is given us.",
            "We all die. The goal isn't to live forever, the goal is to create something that will.",
            "I believe the target of anything in life should be to do it so well that it becomes an art.",
            "Destroying things is much easier than making them.",
            "You need to make a commitment, and once you make it, then life will give you some answers.",
            "Science without religion is lame, religion without science is blind.",
            "A dream is what makes people love life even when it is painful.",
            "Get busy living or get busy dying.",
            "He who does not love his own language is worse than an animal and smelly fish.",
            "Politics is the art of choosing between the disastrous and the unpalatable.",
            "Life is ten percent what happens to you and ninety percent how you respond to it.",
            "History develops, art stands still.",
            "You have enemies? Good. That means you've stood up for something, sometime in your life.",
            "Art is not what you see, but what you make others see.",
            "I hope people remember me for the kind of person that I am, not because of what I do.",
            "Being happy is of the utmost importance. Success in anything is through happiness.",
            "Man is the only creature who refuses to be what he is.",
            "He who controls the past controls the future. He who controls the present controls the past.",
            "Success is attaining your dream while helping others to benefit from that dream materializing.",
            "Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.",
            "Experience is merely the name men gave to their mistakes.",
            "What matters most is how well you walk through the fire.",
            "Some people feel the rain. Others just get wet.",
            "My hope still is to leave the world a bit better than when I got here.",
            "None but ourselves can free our minds.",
            "Man may have discovered fire, but women discovered how to play with it.",
            "Hell is empty and all the devils are here.",
            "Once you say you're going to settle for second, that's what happens to you in life.",
            "It is impossible to love and to be wise.",
            "God has no religion.",
            "When life gives you lemons, squirt someone in the eye.",
            "Fear cuts deeper than swords.",
            "The greater the love, the greater the tragedy when it's over.",
            "Life begins at the end of your comfort zone.",
            "Rather than love, than money, than fame, give me truth.",
            "We waste time looking for the perfect lover, instead of creating the perfect love.",
            "The bravest people are the ones who don’t mind looking like cowards.",
            "I realize now that dying is easy. Living is hard.",
            "Everyone you will ever meet knows something you don't.",
            "Life is about making an impact, not making an income.",
            "Whatever the mind of man can conceive and believe, it can achieve.",
            "Strive not to be a success, but rather to be of value.",
            "Two roads diverged in a wood, and I took the one less traveled by, And that has made all the difference.",
            "I attribute my success to this: I never gave or took any excuse.",
            "You miss 100% of the shots you don’t take.",
            "The most difficult thing is the decision to act, the rest is merely tenacity.",
            "Every strike brings me closer to the next home run.", 
            "Definiteness of purpose is the starting point of all achievement.",
            "Life isn't about getting and having, it's about giving and being.", 
            "Life is what happens to you while you’re busy making other plans.", 
            "We become what we think about.", 
            "Life is 10% what happens to me and 90% of how I react to it.",
            "The most common way people give up their power is by thinking they don’t have any.", 
            "The mind is everything. What you think you become.",  
            "The best time to plant a tree was 20 years ago. The second best time is now.", 
            "An unexamined life is not worth living.", 
            "Eighty percent of success is showing up.",
            "Your time is limited, so don’t waste it living someone else’s life.",
            "Winning isn’t everything, but wanting to win is.", 
            "I am not a product of my circumstances. I am a product of my decisions.", 
            "Every child is an artist.  The problem is how to remain an artist once he grows up.", 
            "You can never cross the ocean until you have the courage to lose sight of the shore.", 
            "Either you run the day, or the day runs you.",
            "Whether you think you can or you think you can’t, you’re right.", 
            "The two most important days in your life are the day you are born and the day you find out why.",
            "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.",
            "The best revenge is massive success.", 
            "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily.", 
            "Life shrinks or expands in proportion to one's courage. ",
            "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.", 
            "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", 
            "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", 
            "The only person you are destined to become is the person you decide to be.",
            "Go confidently in the direction of your dreams.  Live the life you have imagined.", 
            "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.",
            "Certain things catch your eye, but pursue only those that capture the heart.", 
            "Believe you can and you’re halfway there.",
            "Everything you’ve ever wanted is on the other side of fear.", 
            "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
            "Start where you are. Use what you have.  Do what you can.", 
            "Fall seven times and stand up eight.", 
            "Everything has beauty, but not everyone can see.",
            "When I let go of what I am, I become what I might be.",
            "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", 
            "Happiness is not something ready made.  It comes from your own actions.",
            "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.",
            "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground.",
            "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", 
            "Too many of us are not living our dreams because we are living our fears.", 
            "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
            "If you want to lift yourself up, lift up someone else.", 
            "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", 
            "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless.", 
            "You take your life in your own hands, and what happens? A terrible thing, no one to blame.",
            "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", 
            "I didn’t fail the test. I just found 100 ways to do it wrong.", 
            "In order to succeed, your desire for success should be greater than your fear of failure.",
            "A person who never made a mistake never tried anything new.", 
            "The person who says it cannot be done should not interrupt the person who is doing it.",
            "There are no traffic jams along the extra mile.", 
            "It is never too late to be what you might have been.", 
            "You become what you believe.", 
            "I would rather die of passion than of boredom.", 
            "A truly rich man is one whose children run into his arms when his hands are empty.", 
            "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
            "Build your own dreams, or someone else will hire you to build theirs.", 
            "Education costs money.  But then so does ignorance.",
            "I have learned over the years that when one's mind is made up, this diminishes fear.", 
            "It does not matter how slowly you go as long as you do not stop.", 
            "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", 
            "Remember that not getting what you want is sometimes a wonderful stroke of luck.", 
            "You can’t use up creativity.  The more you use, the more you have.", 
            "Dream big and dare to fail.",
            "Our lives begin to end the day we become silent about things that matter.",
            "Do what you can, where you are, with what you have.", 
            "If you do what you’ve always done, you’ll get what you’ve always gotten.", 
            "Dreaming, after all, is a form of planning.",
            "It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live.", 
            "You may be disappointed if you fail, but you are doomed if you don't try.",
            "Remember no one can make you feel inferior without your consent.",
            "Life is what we make it, always has been, always will be.", 
            "The question isn’t who is going to let me; it’s who is going to stop me.", 
            "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", 
            "It’s not the years in your life that count. It’s the life in your years.", 
            "Change your thoughts and you change your world.",
            "Either write something worth reading or do something worth writing.", 
            "Nothing is impossible, the word itself says, “I’m possible!”.", 
            "The only way to do great work is to love what you do.",
            "If you can dream it, you can achieve it.",
            "Difference between success and failure is simple: habits.",
            "Nothing great is going to happen as long as you are holding a negative view of who you are.",
            "Don’t ask: what if I fail? Ask: what if I succeed?",
            "Success is a game, not a war.",
            "As long as you are alive, no goal is impossible. Just don't quit.",
            "You can’t rise above how you see yourself.",
            "Don’t let your self-esteem depend on what others think of you.",
            "Almost all big mistakes are made when we think things are going well.",
            "Say good things about others behind their back.",
            "People don't care how much you know until they know how much you care.",
            "Remember to smile, often. It does not cost anything, cheers those around you and puts you in a better mood. Smile. Now.",
            "Love what you do. Do what you love.",
            "Before you complain about what sucks in your life, ask what is your life trying to teach you?",
            "Your life is not something that someone gives you. Your life is what you choose yourself. You are the one who chooses how you live.",
            "You act like the type of person you believe you are.",
            "Unless you work at a hospital, don’t treat everything in life as an emergency.",
            "Being a leader means being responsible for others.",
            "When you succeed, you will also succeed in making some people unhappy.",
            "Dear God, show me how to take who I am, who I want to be, what I can do, and use me for a purpose greater than myself.",
            "Most of our suffering arises from not being able to sit quietly in a room alone. Try it.",
            "Once a week remind yourself to write down where are you going in your life? Start. Now.",
            "Questions are more important than answers. Asking questions is how you learn. Learning is how you succeed.",
            "If you put others’ approval above your own, you are never going to find out what you love, what you really want, what makes you thrive.",
            "People will follow you when they trust you, not when they fear you.",
            "As long as you are alive, it’s not the end. Everything passes. This too shall pass. Don’t give up.",
            "People with clear goals always outperform people with vague aspirations.",
            "Do something today that makes you say “I love my life.”",
            "You succeed by doing. Not by thinking about doing.",
            "Success is a by-product of your struggles.",
            "Finish what you start.",
            "Point of making money is not to spend on yourself. Money is there to invest, to create, to build, to grow.",
            "If you want to succeed, don’t waste your precious time and energy worrying about what others will think of you.",
            "Don’t second guess what you did. Looking back is only good if it leads to a better future.",
            "If you want to succeed, make sure money is a result, never the objective.",
            "Inspiration starts your motor. Habits keep you going.",
            "There is no such thing as “don’t work hard, work smart.”  If you want to succeed, work smart AND work hard.",
            "If you want to succeed, never stop learning. Read something that teaches you something. Everyday.",
            "Never settle. Never get too comfortable. Stay hungry. Stay humble. Stay striving. Stay succeeding.",
            "Big results start with big ambitions.",
            "You can only get what you desire, what you are hungry for. That’s what motivates you to work hard. And makes you successful.",
            "Instead of complaining about something, do something about it.",
            "If you want to succeed, take responsibility for yourself and others around you.",
            "To succeed, you must first survive.",
            "Don’t complain. Whiners don’t succeed.",
            "Be enthusiastic about things you do. Especially the unpleasant ones.",
            "Secret to a successful relationship: it’s not about you.",
            "To be a millionaire, you have to solve a 10 million dollar problem. To be a billionaire, solve a 10 billion dollar problem.",
            "It’s not only what you plant but also what you cultivate.",
            "Don’t aim low.",
            "If you are not learning, you are not succeeding.",
            "People work harder when they better understand the impact of their work.",
            "Secret of inspiration: people want to be part of something greater than themselves.",
            "If you are not constantly learning, growing and improving, then success is passing you by.",
            "Yesterday I was clever, so I wanted to change the world. Today I am wise. so I am changing myself.",
            "Fall seven times, stand up eight.",
            "There is a big difference of action between “ I want change and I want to change.”",
            "It won’t be easy , but it will be worth it.",
            "You were born an original, do not die a copy.",
            "Do what is right not what is easy.",
            "Every next level of your life will demand a different you.",
            "Life always offers you a chance, it’s called tomorrow.",
            "There are no failures, only quitters.",
            "The first step towards greatness is taking the first step.",
            "No Masterpiece Is Ever Created By A Lazy Artist.",
            "The Past Cannot Be Changed, The Future Is Yet In Your Power.",
            "Work So Hard, People Think That You Are Crazy.",
            "If You Wanna Own A Ferrari, Stop Taking Advice From Toyota Owners.",
            "If You Want To Be Powerful, Educate Yourself.",
            "Stop Thinking, Start Doing.",
            "If You Can't Stop Thinking About It, Don't Stop Working For It.",
            "Work for it more than you talk about it.",
            "Action is the foundational key to all success.",
            "Rule your mind or it will rule you.",
            "Imagination is more important than knowledge.",
            "Love all , trust few. Everything is real but not everyone is true.",
            "Keep working Hard until the doors of your Car open in a vertical way.",
            "Focus on Being Productive Rather than Being Busy.",
            "If it is Important to you, you will find a way. If not you will find a Excuse.",
            "If you are born poor, it's not your fault. But if you die poor, it's your fault.", 
            "It is better to light a candle than curse the darkness.",  
            "All men are created equal. Some work harder in preseason.",
            "When you want to succeed as bad as you want to breathe, then you’ll be successful.",
            "The Way Get Started Is To Quit Talking And Begin Doing.",
            "We Generate Fears While We Sit. We Overcome Them By Action.",

            "If something stands between you and your success, move it. Never be denied.",
            "When you have a clear vision of your goal, it’s easier to take the first step toward it.",
            "To keep winning, I have to keep improving.",
            "Some people want it to happen, some wish it would happen, others make it happen.",
            "If you judge a fish by its ability to climb a tree, it will live it's whole life believing it is stupid.",
            "Giving up doesn't always mean you're weak. Sometimes it means you are strong and smart enough to let go and move on.",
            "Pray more, worry less.",
            "Pain is real. But so is hope.",
            "Wise men are not always silent, but they know when to be.",
            "Life is to short to spend it with the wrong people.",
            "If you ever think about giving up, remember why you held on for so long.",
            "God didn't bring you this far to leave you.",
            "Life isn't about finding yourself, it's about creating yourself.",
            "By becoming the answer to someone's prayer, we often find the answers to our own.",
            "Don't wish, DO!",
            "Count your rainbows, not your thunderstorms.",
            "You can easily judge the character of a man by how he treats those who can do nothing for him. ",
            "The problem is not the problem. The problem is your attitude about the problem.",
            "You're life, your choice, choose wisely.",
            "Respect yourself enough to walk away from anything that no longer grows you.",
            "Take the first step in faith. You don't have to see the whole staircase, just take the first step.",
            "Failure doesn't mean you are a failure... it just means you haven't succeeded yet.",
            "If you're bored with life, if you don't get up every morning with a burning desire to do things - you don't have enough goals.",
            "Find someone who will change your life, not just your status.",
            "Every day holds the possibility of a miracle.",
            "Happiness can be found in the darkest of times, if one only remembers to turn on the light.",
            "Live is to short to take it seriously.",
            "The story of your life has many chapters. One bad chapter doesn't mean it's the end of the book.",
            "If you think education is expensive try ignorance. ",
            "I am in charge of how I feel and TODAY I am choosing HAPPINESS.",
            "You cannot push anyone up the ladder unless he is willing to climb.",
            "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
            "You were born with the ability to change someone's life - don't ever waste it.",
            "Change is hard at first, messy in the middle and gorgeous at the end.",
            "Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like.",
            "Don't make a promise you can't keep.",
            "Fake friends believe in rumors. Real friends believe in you.",
            "Don't ever let anyone steal your dreams.",
            "I am done with the past, the future has plenty of room for change.",
            "Reality is a product of our dreams, decisions & actions.",
            "Live more, complain less. More smiles, less stress. Less hate, more blessed.",
            "Sometimes you have to walk away from what you want to find what you deserve.",
            "The only disability in life is a bad attitude. ",
            "Simplicity is not a simple thing.", 
            "Remind yourself, it's OK not to be perfect.",
            "Do not pray for an easy life; pray for the strength to endure a difficult one.",
            "Every day may not be good but there is something good in every day.",
            "Learn to say 'no' to the good so you can say 'yes' to the best.",
            "I love you not because I need you, I need you because I love you.",
            "Our lives begin to end the day we become silent about things that matter.",
            "Have faith and push on.",
            "You have enemies? Good. That means you've stood up for something, sometime in your life. ",
            "Once you've accepted your flaws, no one can use them against you.",
            "Don't stress. Do your best. Forget the rest.",
            "As long as you can laugh at yourself you will never cease to be amused.",
            "The best way to predict the future is to create it.",
            "Someone else is happy with less than you have.",
            "No matter how slow you go, you are still lapping everybody on the couch.",
            "We all have dreams. But in order 2 make dreams into reality, it takes an awful lot of determination, dedication, & discipline. ",
            "If you want it, work for it!",
            "Winners don't wait for chances, they take them.",
            "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain.",
            "Don't speak unless you can improve the silence.",
            "The key ingredient to any kind of happiness or success is to never give less than your best.",
            "Difficulties in life are intended to make us better, not bitter.",
            "You can't let one bad moment spoil a bunch of good ones.",
            "The difference between who you ARE and who you WANT TO BE is the work you put in.",
            "No matter how far you have gone on the wrong road, you can still turn around.",
            "Today is another chance to get it right.",
            "Finish each day & be done with it. You have done what you could. Learn from it; tomorrow is a new day.", 
            "If you're not part of the solution, you're part of the problem.",
            "The real friendship is like fluorescence, it shines better when everything has darken. ",
            "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. ",
            "Stop looking for reasons to be unhappy. Focus on the things you do have, and the reasons you should be happy.",
            "Live in the moment. Forget the past and don't concern yourself with the future.",
            "Give people a piece of your heart rather than your mind.",
            "Listening is often the only thing needed to help someone.",
            "At this very moment, life is perfect.",
            "Your beliefs don't make you a better person, your behavior does. ",
            "Don't make excuses for why you can't get it done. Focus on all the reasons why you must make it happen.",
            "Do more for the world than it does for you.",
            "If u really want something, & really work hard, & take advantage of opportunities, & never give up, you will find a way.",
            "We can't become what we need to be by remaining what we are.",
            "If you don't step forward you will always remain in the same place.",
            "Money is the wealthy man's curtain which hides all his defects from the world.",
            "Change begins at the end of your comfort zone.",
            "Kind words can be short and easy to speak, but their echoes are truly endless.",
            "When I let go of what's not meant to be, I clear a path for good stuff to find me!",
            "Things that you enjoy are never a waste of time, everything else is suspect.",
            "Be the type of person you want to meet.",
            "You are where you're supposed to be at this very moment. Every experience is part of God's divine plan.",
            "You cannot find peace by avoiding life.",
            "Trust takes years to build, seconds to break and forever to repair.",
            "Decide that you want it more than you are afraid of it.",
            "Look for the good in each day.",
            "Your actions and your words should always agree with each other.",
            "Better to remain silent & be thought a fool that to speak & remove all doubt.",
            "God didn't promise days without pain, sun without rain, but He did promise strength for the day and light for the way.",
            "Your child will follow your example, not your advice.",
            "Laughter is the sound of the soul dancing.",
            "God didn't bring you this far to leave you.",
            "Live simply. Love generously. Speak truthfully. Pray daily. Leave everything else to God.",
            "Accept responsibility for the good and the bad.",
            "Sometimes you gotta fall before you fly.",
            "Everything is going to be alright, maybe not today, but eventually.",
            "There are blessings every day. Find them. Create them. Treasure them.",
            "Be a good listener. Your ears will never get you in trouble. ",
            "Turn your cant's into cans and your dreams into plans.",
            "When love is real, it finds a way.",
            "Great spirits have always faced violent opposition from mediocre minds. ",
            "Why are you trying so hard to fit in when you were born to stand out?",
            "Stars can't shine without darkness.",
            "Good times become good memories and bad times become good lessons.",
            "Don't let someone else's opinion of you become your reality.",
            "You are part of a puzzle in someones life. You may never know where you fit. But, someones life may never be complete without you in it.",
            "Conquer your bad habits or they will conquer you.",
            "There is no pillow so soft as a clear conscience. ",
            "If someone wants you, nothing will keep them away, but if they don't want you, nothing will make them stay!",
            "The best feeling in the world is being loved back by the person you love.",
            "Don't say 'I can't because I'm weak'. Say 'I may be weak, but I'm strong with God.'",
            "Be sure to taste your words before you spit them out.",
            "Love is what makes you smile when you're tired.",
            "One day, you'll be just a memory for some people. Do your best to be a good one.",
            "True love is like a fine wine, the older the better.",
            "You have two ears and one mouth. Follow that ratio. Listen more, talk less.",
            "A Mother's LOVE is WHOLE, no matter how many times DIVIDED.",
            "Life is full of give and take. Give thanks and take nothing for granted.",
            "The beauty of a woman is seen in her eyes, because that is the doorway to her heart, the place where love resides. ",
            "Do everything in love.",
            "It's great to be happy, but it's even better to bring happiness to others.",
            "People too weak to follow their own dreams will always find a way to discourage yours.",
            "Don't lie to people that trust you, and don't trust people that lie to you.",
            "For everything you have lost, you have gained something else.",
            "Why compare yourself with others? No one in the entire world can do a better job of being you than you.",
            "Your value doesn't decrease based on someone's inability to see your worth.",
            "Keep your heels, head and standards high.",
            "Life is too short to wake up with regrets. So love the people who treat you right and forget about the ones who don't.",
            "Music washes away from the soul the dust of everyday life.",
            "Stressed? Let go & let God.",
            "Action expresses priorities.",
            "Love fearlessly.",
            "What worries you masters you.",
            "Don't compare your Chapter 1 to someone else's Chapter 20.",
            "Most people never run far enough on their first wind to find out they've got a second. ",
            "Worry ends when faith begins.",
            "What if you woke up today with only the things you thanked God for yesterday?",
            "Don't worry over what other people are thinking about you. They're too busy worrying over what you are thinking about them.",
            "You only live once, but if you do it right, once is enough.",
            "Good things come to those who wait. But better things come to those who work for it.",
            "Always remember that you are absolutely unique. Just like everyone else.", 
            "To love is to receive a glimpse of HEAVEN.",
            "A woman is like a tea bag: you cannot tell how strong she is until you put her in hot water.",
            "Trust in God. He believes in YOU!",
            "Life is the art of drawing without an eraser.",
            "Never let your memories be greater than your dreams.",
            "Don't cry over the past, it's gone. Don't stress about the future, it hasn't arrived. Live in the present and make it beautiful!",
            "Smile for what you have, rather than cry for what you don't.",
            "LEARN from yesterday, LIVE for today, HOPE for tomorrow.",
            "Everything in life can teach you a lesson, you just have to be willing to learn.",
            "The hardest part about accepting the saying 'everything happens for a reason' is waiting for that reason to come along.",
            "You can tell whether a man is clever by his answers. You can tell whether a man is wise by his questions.",
            "Trust is the hardest thing to find and the easiest to lose.",
            "To improve is to change; to be perfect is to change often.",
            "When something bad happens you have three choices. You can either let it define you, let it destroy you, or you can let it strengthen you.",
            "Don't judge me based on YOUR perception, your jealousy, or what you would do. I don't live my life for you. I live my life for ME.",
            "God is the best listener, you don't need to shout, nor cry out loud. Because He hears even the very silent prayer of a sincere heart.",
            "Don't worry about what others think. People are always negative, don't let it bother you. Stay strong. Move on.",
            "Life is too short to give another minute to anyone or anything that doesn't make you happy.",
            "The life you have left is a gift. Cherish it. Enjoy it now, to the fullest. Do what you want most.",
            "Knowing when to walk away, is wisdom. Being able to, is courage. Walking away with your head held high, is dignity.",
            "Don't treat people as bad as they are, treat them as good as you are.",
            "People are lonely because they build walls instead of bridges.",
            "Your words mean nothing when your actions are the complete opposite.",
            "Be nice to people on your way up because you'll need them on your way down.",
            "People may not always tell you how they feel about you, but they will always show you.",
            "Just because a person smiles all the time doesn't mean their life is perfect. That smile is a symbol of hope and strength.",
            "A positive attitude gives you power over your circumstances instead of your circumstances having power over you.",
            "I want to be the best. I want to be a great. I want to be feared. I want to be unforgettable. I want to be unforgivable. I WANT TO BE ME.",
            "Never lower your head. Hold it high. Look the world straight in the eye.",
            "Respect is for those who deserve it, not for those who demand it.",
            "Before you see the rainbow, you see the rain. If you want to reach your goals, you have to be able to put up with the pain.",
            "Cheer up, although life may not be easy now, in the end it's all worth it, everything will get better in time. So SMILE!",
            "Never regret the moments that once made you smile, because those are the ones you will remember forever.",
            "The less I care, the happier I am.",
            "Why do you choose to be sad, when you can be happy? Remember, it's not what happens to you that matters, it's how you take it.",
            "Sometimes, we have to let go of something that once meant the world to us, not because we want to, but because we have to.",
            "A few tears won't kill you, only heal you. A little pain won't destroy you, only strengthen you. So cry, forgive, and move on.",
            "Sometimes you have to stand alone to prove that you can still stand.",
            "We do not remember days. We remember moments.",
            "Don't promise me things. I don't trust words, I trust actions.",
            "Our steps to achievement: Plan purposefully. Prepare prayerfully. Proceed positively. Pursue persistently.",
            "Somewhere someone is looking for exactly what you have to offer.",
            "Smile: because you're beautiful. Laugh: because your living life to the fullest. Stand strong: because haters can't bring you down.",
            "Talk is cheap, If you like me, tell me. If you miss me, show me. If you love me, prove it.",
            "Push harder than yesterday if you want a different tomorrow.",
            "Let your strengths overcome your weaknesses.",
            "Sometimes you have to get knocked down lower than you've ever been, to stand up taller than you than you ever were.",
            "Take time to appreciate what you have.",
            "Sometimes, you have to stop thinking so much and just go where your heart takes you.",
            "Before you react, think. Before you quit, try.",
            "I may not always be perfect, but I'm always me.",
            "I'm not perfect, I make mistakes, I'm sometimes a bad friend, but I'm really thankful for all I have, I promise.",
            "To uncover your true potential you must first find your own limits and then you have to have the courage to blow past them.",
            "Don't put the key to your happiness in someone else's pocket.",
            "One of the good things about goodbye, is that it means you're a little closer to a new hello.",
            "Everything has beauty, but not everyone sees it.",
            "Believing in yourself is the first secret of success.",
            "Honestly, I don't have time to hate people who hate me, because I'm too busy loving people who love me.",
            "We fear rejection, want attention, crave affection, and dream of perfection.",
            "Hard work + Dreams + Dedication = Success.",
            "Anyone can give up, it's the easiest thing ever. But to hold it together when everyone else thinks you'd fall apart is true strength.",
            "Smile. Let everyone know that today you're a lot stronger than you were yesterday.",
            "Just because one person doesn't seem to care for you, doesn't mean you should forget about everyone else who does.",
            "Don't lose yourself trying to find someone.",
            "Don't let one bad day make you feel like you have a bad life.",
            "Don't give up on things when you think you can fight for it. It's difficult to wait but it's more difficult to regret.",
            "When you want to succeed as bad as you want to breathe, then you’ll be successful.",
            "Whatever the mind can think and perceive, it can achieve. ",
            "The past cannot be changed, the future is yet in your power,",
            "What you do today can improve all of your tomorrows.",
            "Wake up determined go to bed satisfied.",
            "If you cannot do great things, do small things in a great way.",
            "Believe in yourself. You are braver than you think, more talented that you know and capable of more than you can imagine.",
            "You begin by always expecting good things to happen.",
            "It always seems impossible until it’s done.",
            "Don’t stop when you’re tired. Stop when you are done.",
            "Don’t limit your challenges, challenge your limits.",
            "The most common way for people to give up their power is by thinking they don’t have any.",
            "The trouble is, if you don’t risk anything, you risk more.", 
            "Only I can change my life, no one can do it for me,", 
            "People who are crazy enough to think they can change the world are the ones who do.", 
            "One’s finds limits by pushing them.", 
            "I’ve never chased money. It’s always been about what I can do to motivate and inspire.", 
            "Success isn’t overnight. It’s when everyday you get a little better than the day before. It all adds up.", 
            "I am not a product of my circumstances, I am a product of my decisions.", 
            "It’s not about perfect, it’s about effort every single day. That’s where transformation happens. That’s how change occurs.", 
            "Don’t carry your mistakes around with you. Instead place them under your feet and use them as stepping stones to rise above them.",
            "I didn’t get there by wishing for it or hoping for it, but by working for it.", 
            "I believe you can speak things into existence.", 
            "Challenges are gifts that force us to search for a new center or gravity. Don’t fight them. Just find a new way to stand.", 
            "To be successful, you must accept all challenges that come your way. You can’t just accept the ones you like.", 
            "Power to me is the ability to make change in a positive way.",
            "Formal education will make you a living. Self education will make you a fortune.",
            "Security is mostly a superstition. Life is either a daring adventure or nothing.", 
            "Work hard in silence, let success be your noise.", 
            "Success isn’t about how much money you make, it’s about the difference you make in people’s lives.", 
            "Live as if you were to die tomorrow, learn as if you were to live forever.", 
            "Life is hard, but so very beautiful.",
            "The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.", 
            "I am not judged by the number of times I fail, but by the number of times I succeed.", 
            "Why do we close our eyes when we pray, cry, kiss or dream? Because the most beautiful things in life are not seen but felt by the heart.", 
            "Power is not given to you, you have to take it.", 
            "Be humble, be hungry, and always be the hardest worker in the room.", 
            "With a new day comes strength and new thoughts.", 
            "Leaders set high standards. Refuse to tolerate mediocrity or poor performance.", 
            "If it doesn’t challenge you, it doesn’t change you.",
            "There is no passion to be found playing small in settling for a life that is less than the one you are capable of living.", 
            "Dream big and dream fierce.",
            "Every failure is a lesson. If you are not willing to fail, you are not ready to succeed.",
            "We may encounter many defeats but we must not be defeated.", 
            "Don’t be afraid to give up the good for the great.", 
            "Courage doesn’t mean you don’t get afraid. Courage means you don’t let fear stop you.",
            "We are all a little broken, but last time I checked, broken crayons still color the same.",
            "If you want to be successful, prepare to be doubted and tested.",
            "Vision is the art of seeing what is invisible to others.", 
            "We can do no great things, only small things with great love.", 
            "Don’t let what you cannot do interfere with what you can do.", 
            "Just because my path is different doesn’t mean I’m lost.",
            "Life shrinks or expands in proportion to one’s courage.", 
            "Innovation distinguishes between a leader and a follower.",
            "I am not afraid of storms because I am learning how to sail my ship.", 
            "Leadership is the ability to get extraordinary achievement from ordinary people.", 
            "Never regret a day in your life. Good days give you happiness. Bad days give you experience.",
            "To accomplish great things, we must not only act, but also dream. Not only plan but also believe.", 
            "All journeys have secret destinations of which the travelers is unaware.", 
            "Love your enemies because they tell you all your faults.", 
            "If’I had 6 hours to chop down a tree, I would spend the first 4 hours sharpening the axe.", 
            "Leap and the net will appear.",
            "You words can be powerful, they can hurt or uplift you, so think before you speak as every word counts.",
            "Dream is not the thing you see in sleep, but it is that thing that doesn’t let you sleep.", 
            "It’s not the load that keeps you down, it’s how you carry it.",
            "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.", 
            "When your work speaks for itself, don’t interrupt.",
            "Everybody is a genius, but if you judge a fish by it’s ability to climb a tree, it will live it’s whole life thinking it’s stupid.", 
            "Do you want to meet the love of your life? Look in the mirror.", 
            "Be patient with yourself. Self-growth is tender, it’s holy ground. There is no greater investment.", 
            "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.", 
            "Knowing is not enough we must apply. Wishing is not enough, we must do.",
            "Good, better, best. Never let it rest. Til your good is better and your better is best.", 
            "You’ll never change your life until you change something you do daily. The secret of your success if found in your daily routine.",
            "Remember, no one can make you feel inferior without your consent.", 
            "Staying positive doesn’t mean that things will turn out okay. Rather it is knowing that you will be okay no matter how things turn out.",
            "What comes easy won’t last and what lasts won’t come easy.",
            "Old ways won’t open new doors.",
            "Don’t let the fear of losing be greater than the excitement of winning.", 
            "Integrity is the most valuable and respected quality of leadership. Always keep your word,", 
            "The best preparation for tomorrow is doing your best today.", 
            "Be brave, take risks. Nothing can substitute experience.",
            "You only fail when you stop trying.",
            "A river cuts through rock, not because of it’s power but because of it’s persistence.", 
            "With drive and a little talent, you can move mountains.", 
            "That some achieve great success is proof to all that others can achieve it as well.", 
            "We are all broken, that’s how light gets in.", 
            "There are far, far better things ahead than any we leave behind.", 
            "Creativity is intelligence having fun.", 
            "Vibrate so high that toxic people in your life fall back, because they no longer know how to approach you.",
            "The struggle you’re in today is developing the strength you need for tomorrow.",
            "The best way to predict the future is to created it.", 
            "You will never find time for anything. If you want time, you must make it.", 
            "What a wonderful thought it is that some of the best days of our lives haven’t happened yet.",
            "If you believe in yourself, anything is possible.",
            "Life is not measured by the number of breathes we take, but by the moments that take our breathe away.", 
            "I don’t care what you think about me, I don’t think about you at all.",
            "You may have to fight a battle more than once to win it.",
            "Courage is like a muscle, we strengthen it by use.", 
            "Perfection is not attainable, but if we chase perfection we can catch excellence.",
            "I survived because the fire inside me burned brighter than the fire around me.",
            "You can waste your lives drawing lines. Or you can live your life crossing them.", 
            "You don’t want to look back now and know you could have done better.",
            "Keep your eyes on the stars and your feet on the ground.", 
            "The best view comes after the hardest climb.",
            "Either you run the day, or the day runs you.", 
            "Success is getting what you want, happiness is wanting what you get.",
            "Don’t wait on perfect conditions, just go ahead and do something.",
            "Leadership reputations are mad or lost in times of crisis.",
            "Keep your face to the sunshine and you cannot see a shadow.", 
            "Dream big and dare to fail.",
            "Remember that guy who gave up? Yeah neither does anyone else.",
            "When you talk you are only repeating what you already know. But if you listen, you may learn something new.", 
            "Do not wait to strike till the iron is hot, but make it hot by sticking.",
            "Step by step and the thing is done.",
            "Action is the foundational key to all success.", 
            "Pain makes you stronger. Tears make you braver. Heartbreak makes you wiser. So thank the past for a better future.",
            "I never lose, either I win or I learn.",
            "Even the darkest night will end and the sun will rise.", 
            "Stop waiting for good things to happen, go out and make them happen",
            "You can’t use up creativity. The more you use, the more you have.", 
            "Whatever your situation might be, set your mind to whatever you want to do and put a good attitude in it and believe that you can succeed.", 
            "We generate fears while we sit. We overcome them by action.", 
            "What you lack in talent can be made up with desire, hustle and giving 100% all the time.", 
            "The successful warrior is the average man with laser-like focus.", 
            "Life goes on. Whether you choose to move on and take a change in the unknown. Or stay behind, locked in the past thinking of could’ve been.", 
            "To win in the market place, you must first win in the workplace.", 
            "To handle yourself, use your head. To handle others, use your heart.",
            "The darker the night, the brighter the stars. The deeper the grief the closer is God.", 
            "Follow your dreams, or you’ll spend the rest of the time working for someone who did.",
            "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", 
            "In the end, it is important to remember that we cannot become what we need to be by remaining what we are.", 
            "Change is always powerful. Let your hook be always cast in the pool where you least expect it, there will be a fish.",
            "I can’t change the direction of the wind, but I can adjust me sails to always reach my destination.", 
            "Calm mind brings inner strength and self-confidence, so that’s very important for good health.", 
            "Appreciate where you are in your journey. Even if it’s not where you want to be. Every season serves a purpose.",
            "To be the best, you must be able to handle the worst",
            "Difficult roads often lead to beautiful destinations",
            "Becoming is better than being.", 
            "If you spend too much time thinking about one thing, you’ll never get it done.",
            "Hardships often prepare ordinary people for extraordinary destiny.", 
            "Strength doesn’t come from what you can do. It’s comes from the things you once thought you couldn’t do.", 
            "If you don’t design your own life plan, chances are you’ll all into some else’s plan, and guess what they have planned for you? Not much.", 
            "Everyday might not be good, but there is good in everyday.",
            "You cannot live to please everyone else. You have to edify, educated and fulfill your own dreams and destiny.", 
            "I have learned over the years that when one’s mind is made up, this diminishes fear.", 
            "Optimism is the one quality more associated with success and happiness than any other.", 
            "I never see failure as failure, but only as the game I must play to win.", 
            "Be somebody who makes everyone feel like a somebody.",
            "The only way to achieve the possible is to believe it is possible.", 
            "Let me tell you the secret that has led me to my goal. My strength lies solely in my tenacity.",
            "If you want to be successful in this world, you have to follow your passion, not a paycheck.", 
            "I fight while I can fight.",
            "I find that the harder I work, the more success I seem to have.", 
            "Sales are contingent upon attitude of the salesman. Not the attitude of the prospect.", 
            "The key is not the will to win. Everybody has that. It is the will to prepare to win that is important.",
            "Don’t worry about what others think. Most people don’t use their brain very often.", 
            "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live.", 
            "Change your thoughts and you change your world.", 
            "Life isn’t about finding yourself, it is about creating yourself.",
            "Don’t wait to reach your goal to be proud of yourself. Be proud of yourself every step you take.", 
            "An eye for eye only ends up making the whole world blind.", 
            "If you are not willing to risk the usual you will have to settle for ordinary.", 
            "I’ve got a dream that’s worth more than my sleep.",
            "Success is not final and failure is not fatal. It is the courage to continue that counts", 
            "The expert in anything was once a beginner.",
            "Dreams don’t work if you don’t.",
            "The flower doesn’t dream of the bee. It blossoms and the bee comes.", 
            "Your true success in life begins only when you make the commitment to be excellent at what you do.", 
            "Be not afraid of greatness. Some are born great, some achieve greatness and some have greatness thrust upon them.",
            "I don’t have any time to stay up all night worry about what someone has to say about me.", 
            "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
            "If you have the power to make someone happy, do it. The world needs more of that.",
            "We aim above the mark to hit the mark.", 
            "Two things define you. Your patience when you have nothing and your attitude when you have everything.",
            "I say luck is when an opportunity comes along and you are prepared for it.", 
            "If it is important to you, you will find a way, not an excuse.", 
            "Achieve your goals in silence.", 
            "You can do anything you set your mind to.", 
            "Our greatest weakness lies in giving up. The most certain way to succeed is always to try one more time.",
            "Leadership is an action, not a position.", 
            "Make your life a masterpiece. Imagine no limitations on what you be, have or do.", 
            "There are no limits to what you can accomplish, except the limits you place on your own thinking.", 
            "Always do your best. What you plant now, you will harvest later.",
            "A creative man is motivated by the desire to achieve, not by the desire to beat others.", 
            "When the well is dry, we know the worth of water.", 
            "Everything you ever wanted is on the other side of fear.",
            "If you hate starting over, stop quitting.",
            "It is better to live for one day as a lion than for 1000 years as a sheep.", 
            "Motivation is what gets you started. Habit Is what keeps you going.",
            "The starting point of all achievement is desire.", 
            "Failure will never overtake me if my determination for succeed is strong enough.", 
            "Ambition is the path to success. Persistence is the vehicle you arrive in.", 
            "The soul become dyed wit the color of it’s thoughts.", 
            "Failure is the key to success, each mistake teaches us something.", 
            "Definiteness of purpose is the starting point of all achievement.", 
            "Think like a queen, a queen is not afraid to fail. Failure is another stepping stone to greatness.", 
            "If you wait, all that happens is you get older.",
            "Even if you are on the right track, you’ll get run over if you just sit there.", 
            "If you give up on your dreams, what’s left?", 
            "If you really want the key to success, start by doing the opposite of what everyone else is doing.",
            "You miss 100 percent of the shots you never take.",  
            "She quietly expected great things to happen to her, and no doubt that’s one of the reasons why they did.", 
            "Accept then act. Whatever the present moment contains, accept it as if you had chosen it. This will miraculously change your whole life.", 
            "We only fail when we stop learning.", 
            "Failure will not overcome me so long as my will to succeed is stronger.", 
            "Don’t ever be afraid to dream too big. Nothing is impossible. If you believe in yourself, you can acheive it.", 
            "The difficult thing is the decision to act. The rest is merely tenacity.", 
            "How dare you settle for less when the world has made it so easy for you to be remarkable.", 
            "Things work out best for those who make the best of how things work out.",
            "Done is better than perfect.", 
            "To be successful in sales today, it’s imperative to drop your sales mentality and start working with your prospects as if they already hired you.",
            "Start where you are. Use what you have. Do what you can.", 
            "Difficulties in your life don’t come to destroy you, but to help you realize your hidden potential.",
            "If everything seems under control, you’re not going fast enough.", 
            "The secret to joy in work is contained in one word. Excellence. To know how to do something well is to enjoy it.",
            "Energy and persistence conquer all things.", 
            "A person who never made a mistake never tried anything new.", 
            "The only way to do great work is to love what you do.", 
            "The greatest pleasure in life is doing what people say you cannot do.",  
            "Whatever you hold in your mind on a consistent basis is exactly what you will experience in your life.", 
            "Challenges are what make life interesting and overcoming them is what makes life meaningful.", 
            "The secret to change is not on fighting the old, but on building the new.", 
            "If you set goals and go after them with all the determination you can muster, your gifts will take you places that will amaze you.", 
            "The mark of a great man is one who knows when to set aside the important things in order to accomplish the vital ones.",
            "Follow your dreams, you can be whatever you want just try. Don’t be afraid. Think positive, accept changes. Believe in yourself. Never give up.",
            "Ability is what your capable of doing. Motivation determines what you do. Attitude determines how well you do it.",
            "Complaining about a problems without posing a solution is called whining.", 
            "The quieter you become the more you hear.", 
            "We can’t help everyone, but everyone can help someone.", 
            "Never will you have this day again, so make it count.",
            "You can’t be both awesome and negative. Choose one.",
            "Look in the mirror, that’s your competition.",
            "Education is the passport to the future. For tomorrow belongs to those who prepare for it today.",
            "Stress is caused by being here but wanting to be there.", 
            "One of the most important things you can accomplish is just being yourself.", 
            "Talent wins games, but teamwork and intelligence wins championships.", 
            "The first thing that has be to recognized is that one cannot train someone to be passionate. It’s either in their DNA or it’s not.", 
            "Imagine no limitations Decide what’s right and desirable before you decide what’s possible", 
            "Wise men listen and laugh while fools talk.", 
            "Life is short and it is here to be lived.", 
            "If you do not value your time, either will others. Stop giving away your time and talents, start charging for it.",
            "We can easily forgive a child who is afraid of the dark, the real tragedy of life is when men are afraid of the light.", 
            "Success is a lousy teacher. It seduces smart people into thinking they can’t lose.", 
            "Set your goals high, and don’t stop til you get there.", 
            "A ship is always safe at shore, but that is not what it’s built for.", 
            "Thinking should be your capital asset, no matter whatever ups and downs you come across in life.", 
            "The best revenge is massive success.", 
            "I cannot give you the formula for success, but I can give you the formula for failure which is – try to please everybody.", 
            "The greatest glory lies not in never falling, but in rising every time we fall.", 
            "Remember sometimes not getting what you want is a wonderful stroke of luck.",
            "It is during our darkest moments that we must focus to see the light.", 
            "All our dreams can come true if we have the courage to pursue them.", 
            "Change your life, don’t gamble on the future. Act now, without delay.", 
            "We cannot solve our problems with the same thinking we used when we created the.", 
            "First they ignore you, then they laugh at you, then they fight you, then you win.",
            "If you are afraid to fail, then you’re probably going to fail.", 
            "You have to be odd to be No. 1.", 
            "If you are going through hell, keep going.", 
            "Whether you think you can or you think you cant, you’re right.", 
            "The secret to getting ahead is getting started.", 
            "Don’t just stand there! Make something happen.", 
            "Do or do not, there is no try.", 
            "If you want to lift yourself up, lift up someone else.", 
            "If you believe it will work out, you’ll see opportunities. If you believe it won’t you will see obstacles.", 
            "A good plan violently executed now is better than a perfect plan executed next week.", 
            "Be so good they can’t ignore you.", 
            "Certain things catch your eye, but pursue only those what capture the heart.",
            "Don’t stay in bed unless you can make money in bed.",
            "A diamond is a chunk of coal that did well under pressure.",
            "Helping one person might not change the whole world, but it could change the world for one person.",
            "Believe you can and your half way there.", 
            "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
            "A wrong connection will give you a shock throughout your life, but the right one will light up your life.", 
            "Often any decision, even the wrong decision is better than no decision.", 
            "Don’t quit. Suffer now and live the rest of your life as a champion.",
            "Hard times do not create heroes. It is during the hard times when the hero within us is revealed.", 
            "Being responsible sometimes pisses people off.", 
            "I don’t believe in hope. Hope is a beggar. Hope walks through fire, faith leaps over it.", 
            "Courage is resistance to fear, mastery of fear – not the absence of fear.",
            "Success is walking from failure to failure without any loss of enthusiasm.", 
            "Luck always seems to be against the man who depends on it.",
            "We must all learn not only to fear change, but to embrace it enthusiastically and perhaps even more important.", 
            "If you spend your life trying to be good at everything, you will never be great at anything.", 
            "Luck is what happens when preparation meets opportunity.", 
            "If you cannot outplay them, outwork them.", 
            "You just can’t beat the person who never gives up.", 
            "The art of leadership is saying not, not saying yes. It is very easy to say yes.",
            "Press forward, do not stop, do not linger in your journey but strive for the mark set before you.",
            "The primary cause of unhappiness is never the situation. But your thoughts about it.", 
            "Sunny days would be so special if it wasn’t for rain. Joy wouldn’t feel so good if it wasn’t for pain.", 
            "Don’t be afraid of what you want. This is your time the barriers are down.", 
            "He who is not courageous enough to take risks will accomplish nothing in life.", 
            "Don’t raise your voice, improve your argument.",
            "The greatest discovery of any generation is that a human being can alter his life by altering his attitude.", 
            "When people point out your weaknesses, that’s just another opportunity for you to rise above.", 
            "Challenge yourself. It’s the only path to growth.", 
            "Just when the caterpillar thought the world was ending, he turned into a butterfly.", 
            "To live a creative life, we must lose our fear of being wrong.", 
            "People say motivation doesn’t last. Well neither does bathing. That’s why we recommend it daily.", 
            "No matter how hard you work to bring yourself up, there’s someone out there working just as hard to put you down.",
            "Faith is having the strength to trust in something that you can’t see with your eyes or prove scientifically.",
            "When you walk up to opportunities door, don’t knock it. Kick that bitch in, smile and introduce yourself.", 
            "Act as if what you do makes a difference. It does.",
            "The man on top of the mountain didn’t fall there.", 
            "Formula for success. Rise early, work hard, stroke oil.", 
            "Only you have the power to determine whether your future mimics your past.", 
            "Obstacles are those frightful things you see when you take your eyes off your goal.", 
            "Not until we are lost do we begin to truly find ourselves.",
            "Do you love life? Then do not squander time for that’s the stuff life is made of.",
            "You can fail at something you don’t want, so you might as well take a chance at doing what you love.", 
            "Take every chance you get in life, because some things only happen once.", 
            "Great minds discuss ideas, average minds discuss events, small minds discuss people.",
            "If opportunity doesn’t knock, build a door.", 
            "Don’t persuade, defend or interrupt. Be curious be conversational. Be real and listen.",
            "If you’re alive, you’re a creative person.", 
            "I’d rather attempt to do something great and fail, than to attempt nothing and succeed.", 
            "I am going to use all my tools, my God-given ability, and make the best life I can with it.",
            "If something is wrong, fix it now. But train yourself not to worry, worry fixes nothing.", 
            "Well done is better than well said.", 
            "It’s always too early to quit.",
            "The question isn’t who is going to let me, it’s who is going to stop me.",
            "Only put off tomorrow what you are willing to die having left undone.", 
            "The future belongs to those who believe in the beauty of their dreams.", 
            "It’s not whether you get knocked down, it’s whether you get up.", 
            "I attribute my success to this. I never gave or took any excuse.", 
            "There will be obstacles, there will be doubters, there will be mistakes, but with hard work, there are no limits.", 
            "Dream as if you’ll live forever, live as if you’ll die today.",
            "If you don’t stand up for something, you can fall for anything.", 
            "Success is liking yourself, liking what you do and liking how you do it.", 
            "Change the way you look at things, and the things you look at change", 
            "One way to keep momentum is to have constantly greater goals.", 
            "Never give up, for that is just the place and time that the tide will turn.",
            "The pessimist sees difficulty in every opportunity. The optimist sees the opportunity in every difficulty.", 
            "Life is an adventure, it’s not a package tour.", 
            "A winner is just a loser who tried one more time.", 
            "Don’t let yesterday take up too much of today.", 
            "Start by doing what’s necessary, then do what’s possible, then suddenly you are doing the impossible.", 
            "You can make something of your life. It just depends on your drive.",
            "If you want to achieve greatness, stop asking permission.",
            "Life is like a movie. Write your own ending. Keep believing, keep pretending.",
            "Try not to become a person of success, but rather try to become a person of value.",
            "Failure is condiment that gives success it’s flavor.", 
            "Fear is going to be a player in your life, but you get to decide how much.", 
            "How wonderful it is that nobody need wait a single moment before starting to improve the world.", 
            "The only people with you should try to get even with are those who have helped you.", 
            "All progress takes place outside the comfort zone.",
            "As we look ahead into the next century, leaders will be those who empower others.", 
            "Nothing is impossible, the word itself says 'I'm possible!'.",
            "What we achieve inwardly will change outer reality.",
            "The future depends on what you do today.", 
            "People will forget what you said. People will forget what you did, but they will never forget how you made them feel.", 
            "Make each day a masterpiece.", 
            "In every job that must be done, there is an element of fun. You find the fun and snap, the job is a game.", 
            "Even when I was close to my feet, I rose to my feet.", 
            "Do what you have to do to do what you want to do.",
            "I’ve learned that something constructive comes from every defeat,", 
            "What if I fall? Oh, but my darling, what if you fly? ",
            "When people are financially invested, they want a return. When people are emotionally invested, they want to contribute.", 
            "If you light a lamp for someone else, it will also brighten your path.", 
            "Absorb what is useful, discard what its useless and add what it specifically your own.", 
            "We must accept finite disappointment but never lose infinite hope.", 
            "It’s not the years in your life that count. It’s the life in your years.",
            "If you can do what you do best and be happy, you’re further along in life than most people.",
            "A good leader is a person who takes a little more than his share of the blame and little less than his share of credit.", 
            "At some pointing you have to divorce yourself from doing the things that other people want from you.",
            "Dealing with back stabbers, there was one thing I learned, they’re only powerful when you’ve got your back turned.",
            "Even if you fall on your face, you are still moving forward.", 
            "Know your fears to your self, but share your courage with others.", 
            "I’ve failed over and over and over again and that is why I succeed.", 
            "Your own resolution to succeed is more important that any others.", 
            "By putting in that intense form of stress, it makes regular life more peaceful.",
            "If you can’t make it better, you can laugh at it.", 
            "Forget about the fast lane. If you really want to fly, just harness your power to your passion.", 
            "I don’t dream at night, I dream at day. I dream all day. I dream for a living.", 
            "The world you desire can be won. It exists. It is real. It is possible. It is yours.",  
            "Motivation is when your dreams put on work clothes.",
            "The power you have is to be the best version of yourself you can be, so you can create better world.",
            "The best way out is always through.",
            "Not knowing you can’t do something is sometimes all it takes to do it.", 
            "It’s life. You don’t figure it out. You just climb up on the beast and ride.",
            "Speak softly and carry a big stick.", 
            "There is only one way to avoid criticism. Do nothing. Be nothing. Say nothing.", 
            "Don’t judge each day by the harvest you reap but by the seeds that you plant.",
            "Have the courage to follow your heart and intuition, they somehow know what you truly want to become.",
            "Forget the pain, mock the pain. Reduce it and laugh.",
            "Real courage is when you know you’re licked before you begin, but you begin anyway and see it through no matter what.",
            "There is zero correlation between being the best talker and having the best ideas.", 
            "You will never plow a field if you only turn it over in your mind.", 
            "Nothing is permanent in this wicked world, not even our troubles.", 
            "A normal life is boring.",
            "It isn’t the climb that wear you out, it is the pebble in your shoe.", 
            "Each day provides it’s own gifts.", 
            "Sometimes you face difficulties, not because you have done something wrong, but because you have done something right",
            "Learning never exhausts the mind.",  
            "We must let go of the life we have planned so as to accept the one that is waiting for us.", 
            "Whatever or do dream you can do. Begin it. Boldness has genius and power and magic in it.", 
            "A dream doesn’t become a reality through magic. It takes sweat, determination and hard work.",
            "Genius is poor not paid.", 
            "Do what you have to do until you can do what you want to do.",
            "The day is what you make of it. SO why not make it a great one.", 
            "I am no longer accepting the things I can’t change, I am going to change the things I can’t accept.",
            "To move the world we must first move ourselves.", 
            "Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from.", 
            "Try to be a rainbow in someones cloud.", 
            "Success seems to be connect with action. Successful people keep moving. They make mistakes, but they don’t quit.",
            "Outstanding people have one thing in common. An absolute sense of mission.", 
            "You may kill me with your hatefulness but like air I’ll rise.", 
            "Find who you are in this world and what you need to feel good alone. I think that’s the most important thing in life.", 
            "Your ability to adapt to failure, and navigate your way out of it, absolutely 100 percent makes you who you are.", 
            "Every mountain top is within your reach if you just keep climbing.",
            "Sometimes you will never know the value of a moment until it becomes a memory.", 
            "When we strive to become better than we are, everything around us becomes better too.", 
            "Intelligence without ambition is a bird without wings.", 
            "Imitation is suicide.",
            "I can’t go back to yesterday because I was a different person then.", 
            "Don’t go around saying the world owes you a living. The world owes you nothing. It was here first.",
            "I have never learned anything from any man who agreed with me.",
            "Those who don’t believe in magic will never find it.", 
            "If we challenge convention, we can solve any problem.", 
            "Excellence is not a skill. It is an attitude.",
            "It is never too late to be what you might have been.", 
            "If all you can do is crawl, then start crawling.", 
            "If you are willing to do more than you are paid to do, eventually you will be paid to do more than you do.",
            "What would you attempt if you knew you would not fail.", 
            "Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them.", 
            "I am not a product of my circumstances, I am a product of my decisions.", 
            "The number one reason people fail in life is that they listen to their friends, family and neighbors.", 
            "You wouldn’t worry so much about what others think about you if you realized how seldom they do.", 
            "Life is like riding a bicycle. In order to maintain balance you must keep moving.", 
            "No matter where life takes me, find me with a smile.", 
            "There is no mountain I cant climb. No tower too high. No plane that I can’t learn how to fly.", 
            "If you aren’t sincere with it, you shouldn’t say anything at all."



};

    CardView cardView1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        myPager=findViewById(R.id.myPager);
        Collections.shuffle(Arrays.asList(quotes));
        Arrays.toString(quotes);
        myAdapter adapter=new myAdapter(this, quotes, new myAdapter.CallBack() {
            @Override
            public void onLongClick(CardView cardView) {
                cardView1=cardView;
                ActivityCompat.requestPermissions(MainActivity.this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, 200);
            }
        });
        myPager.setAdapter(adapter);
        Toast.makeText(this, "HOLD THE QUOTE TO SAVE", Toast.LENGTH_LONG).show();

    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[]permissions,int[] grantResults ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == 200) {
            Toast.makeText(this, "QUOTE SAVED", Toast.LENGTH_LONG).show();
            Bitmap ss=Bitmap.createBitmap(cardView1.getWidth(), cardView1.getHeight(), Bitmap.Config.ARGB_8888);
            Canvas canvas=new Canvas(ss);
            cardView1.draw(canvas);
            MediaStore.Images.Media.insertImage(
                    getContentResolver(),
                    ss,
                    "Image",
                    "Captured ScreenShot"
            );
            this.cardView1 = null;
        }
    }
}
